name: base
channels:
  - defaults
dependencies:
  - python=3.12
  - conda==24.11.3
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - menuinst
  - console_shortcut_miniconda
  - powershell_shortcut_miniconda
  - anaconda-anon-usage
  - scipy
  - seaborn
  - scikit-learn
  - numpy
  - sqlalchemy
  - lxml
  - html5lib
  - beautifulsoup4
  - matplotlib
  - conda-pack
